- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import VPC Variables
      include_vars: vars/vpc_setup

    - name: Create vprofile VPC
      ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpcCidr}}"
        region: "{{region}}"
        dns_support: yes
        dns_hostnames: yes
        tenancy: default
        state: "{{state}}"
      register: vpcout

    # - debug:
    #     var: vpcout

    - name: Create Public Subnet 1 zone1
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{zone1}}"
        state: "{{state}}"
        cidr: "{{PubSub1Cidr}}"
        map_public: yes
        resource_tags:
          Name: vprofile-pubsub1
      register: pubsubout1_out

    - name: Create Public Subnet 2 in zone2
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{zone2}}"
        state: "{{state}}"
        cidr: "{{PubSub2Cidr}}"
        map_public: yes
        resource_tags:
          Name: vprofile-pubsub2
      register: pubsubout2_out

    - name: Create Public Subnet 3 in zone3
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{zone3}}"
        state: "{{state}}"
        cidr: "{{PubSub3Cidr}}"
        map_public: yes
        resource_tags:
          Name: vprofile-pubsub3
      register: pubsubout3_out

    - name: Create Private Subnet 1 in zone1
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{zone1}}"
        state: "{{state}}"
        cidr: "{{PriSub1Cidr}}"
        map_public: yes
        resource_tags:
          Name: vprofile-prisub1
      register: prisubout1_out

    - name: Create Private Subnet 2 in zone1
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{zone2}}"
        state: "{{state}}"
        cidr: "{{PriSub2Cidr}}"
        map_public: yes
        resource_tags:
          Name: vprofile-prisub2
      register: prisubout2_out

    - name: Create Private Subnet 3 in zone1
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{zone3}}"
        state: "{{state}}"
        cidr: "{{PriSub3Cidr}}"
        map_public: yes
        resource_tags:
          Name: vprofile-prisub3
      register: prisubout3_out

    - name: Internet Gateways
      ec2_vpc_igw:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        state: "{{state}}"
        resource_tags:
          Name: vprofile-igw
      register: igw_out

    - name: Set up public subnet route table
      ec2_vpc_route_table:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        subnets:
          - "{{pubsubout1_out.subnet.id}}"
          - "{{pubsubout2_out.subnet.id}}"
          - "{{pubsubout3_out.subnet.id}}"
        resource_tags:
          Name: vprofile-public-subnet-route-table
      register: pubroutetable1

    - name: Set up Public subnet route table
      ec2_vpc_route_table:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        subnets:
          - "{{pubsubout1_out.subnet.id}}"
          - "{{pubsubout2_out.subnet.id}}"
          - "{{pubsubout3_out.subnet.id}}"
        resource_tags:
          Name: vprofile-public-subnet-route-table
      register: pubroutetable1

    - name: Set up Private subnet route table
      ec2_vpc_route_table:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        subnets:
          - "{{prisubout1_out.subnet.id}}"
          - "{{prisubout2_out.subnet.id}}"
          - "{{prisubout3_out.subnet.id}}"
        resource_tags:
          Name: vprofile-private-subnet-route-table
      register: priroutetable1
